### ISSUE TITLE
chore: cleanup

### ISSUE THREAD

**Issue by dargmuesli** [maevsi/sqitch#78]
The following ideas for changes in the overall code base came up:
- [x] use `TIMESTAMPTZ`, not just `TIMESTAMP`: https://github.com/maevsi/sqitch/pull/92
- [x] use standardized `CURRENT_TIMESTAMP`, not the postgres specific `NOW()`: #93
- [x] extract the `NULLIF(current_setting('jwt.claims.account_id', true), '')::UUID IS NOT NULL AND...` occurrences into a separate function: https://github.com/maevsi/sqitch/pull/101
- [x] use `created_at`, not just `created`: #91
- [x] remove sqitch dependency comments in source files: #90

As usual, those changes would be breaking with the current deployment style of migrations, so all changes should be released together to keep maintenance work minimal.

cc @sthelemann
